In [34]:
import simple_grid
from q_learning_skeleton import *
import gym
import time 

In [37]:
def act_loop(env, agent, num_episodes):
    for episode in range(num_episodes):
        state = env.reset()

        print('---episode %d---' % episode)

#         time.sleep(3)
    
        renderit = True
        # if episode % 10 == 0:
        #     renderit = True

        for t in range(MAX_EPISODE_LENGTH):
            #if renderit:
            #    env.render()
            #    time.sleep(0.5)
            # printing=False
            # if t % 500 == 499:
            #     printing = True

            # if printing:
            #     print('---stage %d---' % t)
            #     agent.report()
            #     print("state:", state)
            # pick a random action in case we need for 1-epsion case.
            random_action = env.action_space.sample()

            action = agent.select_action(state, random_action)

            new_state, reward, done, info = env.step(action)
            # if printing:
            #     print("act:", action)
            #     print("reward=%s" % reward)

            agent.process_experience(state, action, new_state, reward, done)
            state = new_state
            if done:
                print("Episode finished after {} timesteps".format(t+1))
                env.render()
                agent.report()
                break
    env.close()


In [39]:
#env = simple_grid.DrunkenWalkEnv(map_name="walkInThePark")
env = simple_grid.DrunkenWalkEnv(map_name="theAlley")
num_a = env.action_space.n

if (type(env.observation_space)  == gym.spaces.discrete.Discrete):
    num_o = env.observation_space.n
else:
    raise("Qtable only works for discrete observations")

discount = DEFAULT_DISCOUNT
ql = QLearner(num_o, num_a, discount) #<- QTable
act_loop(env, ql, NUM_EPISODES)


---episode 0---
Episode finished after 103 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 1---
Episode finished after 23 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 2---
Episode finished after 148 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 3---
Episode finished after 37 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 4---
Episode finished after 139 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 5---
Episode finished after 29 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 6---
Episode finished after 75 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 7---
Episode finished after 44 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 8---
Episode finished after 145 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 9---
Episode finished after 13 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 10---
Episode finished a

Episode finished after 87 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 84---
Episode finished after 14 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 85---
Episode finished after 120 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 86---
Episode finished after 81 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 87---
Episode finished after 167 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 88---
Episode finished after 10 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 89---
Episode finished after 49 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 90---
Episode finished after 89 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 91---
Episode finished after 61 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 92---
Episode finished after 47 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 93---
Episode finished after 16 time

 (last action was 'Down')
S...H...H...G
---
---episode 208---
Episode finished after 19 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 209---
Episode finished after 12 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 210---
Episode finished after 159 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 211---
Episode finished after 56 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 212---
Episode finished after 17 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 213---
Episode finished after 19 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 214---
Episode finished after 37 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 215---
Episode finished after 19 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 216---
Episode finished after 59 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 217---
Episode finished after 124 timesteps
 (last action w

Episode finished after 32 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 351---
Episode finished after 97 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 352---
Episode finished after 75 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 353---
Episode finished after 28 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 354---
Episode finished after 81 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 355---
Episode finished after 50 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 356---
Episode finished after 86 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 357---
Episode finished after 23 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 358---
Episode finished after 97 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 359---
Episode finished after 206 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 360---
Episode finished after

S...H...H...G
---
---episode 498---
Episode finished after 94 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 499---
Episode finished after 41 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 500---
Episode finished after 39 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 501---
Episode finished after 180 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 502---
Episode finished after 25 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 503---
Episode finished after 54 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 504---
Episode finished after 39 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 505---
Episode finished after 67 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 506---
Episode finished after 7 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 507---
Episode finished after 15 timesteps
 (last action was 'Down')
S...H...H...G
---
---epi

Episode finished after 73 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 582---
Episode finished after 11 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 583---
Episode finished after 214 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 584---
Episode finished after 53 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 585---
Episode finished after 23 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 586---
Episode finished after 55 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 587---
Episode finished after 36 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 588---
Episode finished after 108 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 589---
Episode finished after 63 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 590---
Episode finished after 22 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 591---
Episode finished afte

Episode finished after 68 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 661---
Episode finished after 142 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 662---
Episode finished after 94 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 663---
Episode finished after 22 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 664---
Episode finished after 56 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 665---
Episode finished after 109 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 666---
Episode finished after 46 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 667---
Episode finished after 25 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 668---
Episode finished after 103 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 669---
Episode finished after 15 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 670---
Episode finished after

Episode finished after 170 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 741---
Episode finished after 169 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 742---
Episode finished after 160 timesteps
 (last action was 'Left')
S...H...H...G
---
---episode 743---
Episode finished after 102 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 744---
Episode finished after 43 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 745---
Episode finished after 49 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 746---
Episode finished after 47 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 747---
Episode finished after 89 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 748---
Episode finished after 43 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 749---
Episode finished after 28 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 750---
Episode finished aft

Episode finished after 102 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 897---
Episode finished after 33 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 898---
Episode finished after 71 timesteps
 (last action was 'Down')
S...H...H...G
---
---episode 899---
Episode finished after 75 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 900---
Episode finished after 50 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 901---
Episode finished after 30 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 902---
Episode finished after 34 timesteps
 (last action was 'Right')
S...H...H...G
---
---episode 903---
Episode finished after 23 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 904---
Episode finished after 57 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 905---
Episode finished after 92 timesteps
 (last action was 'Up')
S...H...H...G
---
---episode 906---
Episode finished after 99 

In [40]:
print(ql.q_table)

[[ 1.06594731  1.37193976  0.65328947  1.26210814]
 [ 1.35519522  0.77166216  1.73979875  1.01932922]
 [ 0.85057692  1.63508064  0.33686688  2.05394247]
 [ 2.36505352  0.7766271   0.65003754  0.34571993]
 [-0.78431014 -2.9557131   0.70108653 -0.86286787]
 [ 1.17207488  1.6064877   2.48577164  1.95731599]
 [ 2.02028654  2.47298407  0.75709342  2.57385375]
 [ 1.96909894  0.62042215  0.55084921  0.6793043 ]
 [-1.24269409 -1.49135004 -0.16209656 -3.47745636]
 [ 0.84706521  1.7794124   1.79999691  1.66247833]
 [ 1.79710452  1.79845289  1.79995697  1.79481387]
 [ 1.77605497  2.44613485  7.677861    3.37266669]
 [ 0.          0.          0.          0.        ]]


In [45]:
[ql.q_table, np.argmax(ql.q_table, axis=1)]

[array([[ 1.06594731,  1.37193976,  0.65328947,  1.26210814],
        [ 1.35519522,  0.77166216,  1.73979875,  1.01932922],
        [ 0.85057692,  1.63508064,  0.33686688,  2.05394247],
        [ 2.36505352,  0.7766271 ,  0.65003754,  0.34571993],
        [-0.78431014, -2.9557131 ,  0.70108653, -0.86286787],
        [ 1.17207488,  1.6064877 ,  2.48577164,  1.95731599],
        [ 2.02028654,  2.47298407,  0.75709342,  2.57385375],
        [ 1.96909894,  0.62042215,  0.55084921,  0.6793043 ],
        [-1.24269409, -1.49135004, -0.16209656, -3.47745636],
        [ 0.84706521,  1.7794124 ,  1.79999691,  1.66247833],
        [ 1.79710452,  1.79845289,  1.79995697,  1.79481387],
        [ 1.77605497,  2.44613485,  7.677861  ,  3.37266669],
        [ 0.        ,  0.        ,  0.        ,  0.        ]]),
 array([1, 2, 3, 0, 2, 2, 3, 0, 2, 2, 2, 2, 0])]